### PR TITLE
Created a new sign up form for new users. Choose role, school

### PR DESCRIPTION
**Pull request by Inthisstyle66**
When user is creating a new account, they will now fill out a form asking for their role, name, email. Depending on role, different info may be asked. 

This is basic info for all roles in screenshot below. 
Screenshot 2023-08-16 at 3 37 53 PM

This is extra information depending on if role is student or not. 
Screenshot 2023-08-16 at 3 39 17 PM
Screenshot 2023-08-16 at 3 39 11 PM

### CODE REVIEW

**Review by venusvli — CHANGES_REQUESTED** [review]
I like the two new options that you created for the sign up form; they can come in handy whenever we want to analyze our user demographic.

Some feedback:
- The "select your enrollment year" option only goes back to 2023, which excludes students who have already enrolled but still want to experience the virtual tours. I think the earliest year should go back to 4 years before the present, at least.
- I would like to propose some appearance changes to the "You are signed in" message: Remove the black background + border, change its position to the header (like in the attachment), and make the text color rgb(138, 0, 0) like the rest of the header text.
- Screen Shot 2023-08-18 at 12 29 37 PM
- Add a "You are signed in" message when a user is signed in after creating a new account 
- Add a "You are signed out" message when the user signs out of their account

**Comment by venusvli** [comment]
Also, I'm not sure why the sign-in form asks me to pick an enrollment date when I choose the "parent" or "educator" options. It should probably only ask that for the "student" option.

**Comment by Inthisstyle66** [comment]
> I like the two new options that you created for the sign up form; they can come in handy whenever we want to analyze our user demographic.
> 
> Some feedback:
> 
> * The "select your enrollment year" option only goes back to 2023, which excludes students who have already enrolled but still want to experience the virtual tours. I think the earliest year should go back to 4 years before the present, at least.
> * I would like to propose some appearance changes to the "You are signed in" message: Remove the black background + border, change its position to the header (like in the attachment), and make the text color rgb(138, 0, 0) like the rest of the header text.
> * Screen Shot 2023-08-18 at 12 29 37 PM
> * Add a "You are signed in" message when a user is signed in after creating a new account
> * Add a "You are signed out" message when the user signs out of their account

Hi Venus, I've added all of the features as shown in this following set of screenshots. I also added a feature that will change the prompt for enrollment depending on the person's role. 


Screenshot 2023-08-21 at 8 30 59 PM
Screenshot 2023-08-21 at 8 30 21 PM
Screenshot 2023-08-21 at 8 11 10 PM
Screenshot 2023-08-21 at 8 09 45 PM
Screenshot 2023-08-21 at 8 09 39 PM
Screenshot 2023-08-21 at 8 09 28 PM

**Comment by venusvli** [comment]
Great fixes; these changes will provide users with a much better sign-in experience.

**Pull request merged**
